# Generated by Django 3.2.4 on 2021-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='stuff/')),
                ('facebook_url', models.URLField(max_length=250)),
                ('twitter_url', models.URLField(max_length=250)),
                ('googel_plus_url', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Stuff',
            },
        ),
    ]
