# Generated by Django 3.2.4 on 2021-06-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='googel_plus_url',
            new_name='instagram_url',
        ),
    ]
