# Generated by Django 3.2.4 on 2021-06-14 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('hook', models.CharField(max_length=350)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_published', models.DateField(auto_now=True)),
                ('time_published', models.TimeField(auto_now=True)),
                ('bg_cover', models.ImageField(default=None, upload_to='blog-posts-bg/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
