# Generated by Django 3.2.4 on 2021-06-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210616_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commments',
        ),
    ]
